export const TABLE_ADD_REQUEST ='TABLE_ADD_REQUEST'
export const TABLE_ADD_SUCCESS ='TABLE_ADD_SUCCESS'
export const TABLE_ADD_FAIL ='TABLE_ADD_FAIL'

export const USER_ADD_REQUEST ='USER_ADD_REQUEST'
export const USER_ADD_SUCCESS ='USER_ADD_SUCCESS'
export const USER_ADD_FAIL ='USER_ADD_FAIL'


export const TABLE_UPDATE_REQUEST ='TABLE_UPDATE_REQUEST'
export const TABLE_UPDATE_SUCCESS ='TABLE_UPDATE_SUCCESS'
export const TABLE_UPDATE_FAIL ='TABLE_UPDATE_FAIL'

export const TABLE_DETAIL_REQUEST ='TABLE_DETAIL_REQUEST'
export const TABLE_DETAIL_SUCCESS ='TABLE_DETAIL_SUCCESS'
export const TABLE_DETAIL_FAIL ='TABLE_DETAIL_FAIL'

export const TABLE_LOGIN_REQUEST=' TABLE_LOGIN_REQUEST'
export const TABLE_LOGIN_SUCCESS=' TABLE_LOGIN_SUCCESS'
export const TABLE_LOGIN_FAIL=' TABLE_LOGIN_FAIL'

export const REMOVE_INFO=' REMOVE_INFO'
// export const DETAIL_RESET=' DETAIL_RESET'
