export const TABLE_ADD_REQUEST ='TABLE_ADD_REQUEST'
export const TABLE_ADD_SUCCESS ='TABLE_ADD_SUCCESS'
export const TABLE_ADD_FAIL ='TABLE_ADD_FAIL'

export const TABLE_DETAIL_REQUEST ='TABLE_DETAIL_REQUEST'
export const TABLE_DETAIL_SUCCESS ='TABLE_DETAIL_SUCCESS'
export const TABLE_DETAIL_FAIL ='TABLE_DETAIL_FAIL'
